export { default as Home } from "./Home/Home";
export { default as LoginPage } from "./Login";
export { default as CheckingPage } from "./Checksession";
export { default as CustomersPage } from "./Customers/Customers";
export { default as Report } from "./Report";
export { default as Welcome } from "./AdminStatic/Welcome";
export { default as password } from "./Resetpassword";
export { default as JobSchedule } from "./JobSchedule";
export { default as CreateUser } from "./Users/CreateUser";
export { default as Users } from "./Users/Users";
export { default as Dashboard } from "./Dashboard";
export { default as ReportOnDemand } from "./ReportOnDemand";
export { default as NewDevice } from "./Device/NewDevice";
export { default as Devices } from "./Device/Devices";
export { default as Consumers } from "./Consumers";
export { default as Simulator } from "./Device/Simulator";
export { default as BulkUpload } from "./Device/BulkUpload";
export { default as ThreeSixty } from "./Device/ThreeSixtyDegree";
export { default as SelfDevice } from "./Device/SelfDevice";

export { default as Metersave } from "./StaticUI/Metersave";
export { default as Metersearch } from "./StaticUI/Searchnewmeter";
export { default as View360Degree } from "./StaticUI/View360Degree";
export { default as Createticket } from "./StaticUI/Createticket";
export { default as DashboardStatic } from "./StaticUI/DashboardStatic";
export { default as BulkUploadMeters } from "./StaticUI/BulkUploadMeters";
export { default as MeterInsident } from "./StaticUI/MeterInsident";
export { default as MeterInsidentSearch } from "./StaticUI/MeterInsidentSearch";
export { default as SearchCommonDetails } from "./StaticUI/SearchCommonDetails";
export { default as CreateInsidentReport } from "./StaticUI/CreateInsidentReport";
export { default as FrequentInsidentReport } from "./StaticUI/FrequentInsidentReport";
export { default as MeterBasicInformationReport } from "./StaticUI/MeterBasicInformationReport";
export { default as MeterInstantInformationReport } from "./StaticUI/MeterInstantInformationReport";
export { default as MeterBillingInformationReport } from "./StaticUI/MeterBillingInformationReport";
export { default as MeterDailyLoadInformationReport } from "./StaticUI/MeterDailyLoadInformationReport";
export { default as Roles } from "./StaticUI/Roles";
export { default as Permissions } from "./StaticUI/Permissions";
export { default as AdminDashboard } from "./StaticUI/AdminDashboard";
export { default as AddConsumer } from "./StaticUI/AddConsumer";
export { default as AddMeter } from "./StaticUI/AddMeter";
export { default as AllCustomer } from "./StaticUI/AllCustomer";
export { default as MonthlyConsumption } from "./StaticUI/MonthlyConsumption";
export { default as ActiveCustomer } from "./StaticUI/ActiveCustomer";
export { default as InActiveCustomer } from "./StaticUI/InActiveCustomer";
export { default as Controls } from "./StaticUI/Controls";
export { default as MonthlyMaintenance } from "./StaticUI/MonthlyMaintenance";
export { default as SettingStatus } from "./StaticUI/SettingStatus";
export { default as  BillingGenerate  } from "./StaticUI/BillingGenerate";
export { default as  BillingGenerateStatus  } from "./StaticUI/BillingGenerateStatus";
export { default as  BillingReport  } from "./StaticUI/BillingReport";
export { default as  PaymentHistory  } from "./StaticUI/PaymentHistory";
export { default as  AdminControl  } from "./StaticUI/AdminControl";
export { default as  Searchadmincontrol  } from "./StaticUI/Searchadmincontrol";
export { default as  Icareunits  } from "./AdminStatic/Icareunits";
export { default as  Operatingunits  } from "./AdminStatic/Operatingunits";  
export { default as  Permission  } from "./AdminStatic/Permissions";  
export { default as  Role  } from "./AdminStatic/Role";  
export { default as  Userlists  } from "./AdminStatic/Userlists";  
export { default as  Workflowconditions  } from "./AdminStatic/Workflowconditions";  
export { default as  Workflowconditionvalues  } from "./AdminStatic/Workflowconditionvalues"; 
export { default as  Workflows  } from "./AdminStatic/Workflows"; 
export { default as  Workflowsactors  } from "./AdminStatic/Workflowactors"; 
export { default as  Workflowstage  } from "./AdminStatic/Workflowstage"; 
export { default as  Workflowtask  } from "./AdminStatic/Workflowtask";
export { default as  AssignMeter  } from "./StaticUI/AssignMeter";
export { default as  ViewMeter  } from "./StaticUI/ViewMeter";
export { default as  Ticketcategory  } from "./StaticUI/Ticketcategory";
export { default as  Commondetails  } from "./StaticUI/Commondetails";
export { default as  Ticketsubcategory  } from "./StaticUI/Ticketsubcategory";
export { default as  MeterBlockLoadInformationReport  } from "./StaticUI/MeterBlockLoadInformationReport";
export { default as  MeterNamePlateReport  } from "./StaticUI/MeterNamePlateReport";
export { default as  MeterEventInformationReport  } from "./StaticUI/MeterEventInformationReport";
export { default as  ProcessScheduler  } from "./StaticUI/ProcessScheduler";
export { default as  CreateReport  } from "./StaticUI/CreateReport";
export { default as  MeterCredentials  } from "./StaticUI/MeterCredentials";
export { default as  RolePermissionMap  } from "./AdminStatic/RolePermissionMap";
export { default as  Newshowticket  } from "./StaticUI/Newshowtickets";
export { default as  Passwordpolicy  } from "./StaticUI/Passwordpolicy";
export { default as  Rcreporting  } from "./StaticUI/Rcreporting";
export { default as  ViewRawData  } from "./StaticUI/ViewRawData";
export { default as  showtickets } from "./StaticUI/Showtickets";
export { default as Aapermissions } from "./AdminStatic/Aapermissions";
export { default as Aarolespermission } from "./AdminStatic/Aarolespermission";
export { default as Aaroles } from "./AdminStatic/Aaroles";
export { default as PasswordchangePage } from "./Forgotpassword";
export { default as ResetpasswordPage } from "./Resetpassword";
export { default as setPassword } from "./AdminStatic/Changingpassword";
export { default as Newmeterthreesixty } from "./StaticUI/Newmeter360";
export { default as Newmetersearch } from "./StaticUI/Newmeterinfo";
export { default as Meterlifecyclereport } from "./StaticUI/Meterlifecyclereport";
export { default as Newviewmeter} from "./StaticUI/Newviewmeter";
export { default as Newactualblockload} from "./StaticUI/Newactualblockload";
export { default as Newactualinstant} from "./StaticUI/Newactualinstant";
export { default as Newactualnameplate} from "./StaticUI/NewactualNameplate";
export { default as Newactualbilling} from "./StaticUI/Newactualbilling";
export { default as Newactualtamperevent} from "./StaticUI/Newtamperevent";
export { default as newactualdailyload} from "./StaticUI/Newactualdailyload";
export { default as Metermap} from "./StaticUI/Metermap";
export { default as Meterdate} from "./StaticUI/Meterdate";
export { default as Actualblocksearch} from "./StaticUI/Actualblocksearch";
export { default as Averagevoltage} from "./StaticUI/Averagevoltage";
export { default as Powerfactor} from "./StaticUI/Powerfactor";